sudo: false
language: python
dist: xenial
git:
  depth: 10
notifications:
  email: false

python:
  - "3.5"
  - "3.6"
  # - "3.7-dev"

install:
  - pip install tox-travis python-coveralls

script:
  - tox -c tox.ini -e pep8
  - tox

after_script:
  - coveralls
